package com.banka.services.izvod;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.logging.Logger;

import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;

import com.banka.models.presek.GetPresekResponse.Stavke;
import com.banka.models.presek.GetPresekResponse.Stavke.Stavka;
import com.banka.models.presek.GetPresekResponse.Zaglavlje;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-18T15:58:18.771+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "izvod",
                      portName = "izvodSOAP",
                      targetNamespace = "ftn.xml",
                      wsdlLocation = "WEB-INF/wsdl/izvod.wsdl",
                      endpointInterface = "xml.ftn.Izvod")
                      
public class IzvodImpl implements Izvod {

    private static final Logger LOG = Logger.getLogger(IzvodImpl.class.getName());

    /* (non-Javadoc)
     * @see xml.ftn.Izvod#getPresek(java.lang.String  brojRacuna ,)javax.xml.datatype.XMLGregorianCalendar  datum ,)int  redniBrojPreseka ,)presek.xml.ftn.PresekIzvoda.Zaglavlje  zaglavlje ,)presek.xml.ftn.PresekIzvoda.Stavke  stavke )*
     */
    public void getPresek(String brojRacuna, XMLGregorianCalendar datum,
			int redniBrojPreseka, Holder<Zaglavlje> zaglavlje,
			Holder<Stavke> stavke) {
    	LOG.info("Executing operation getPresek");
        System.out.println(brojRacuna);
        System.out.println(datum);
        System.out.println(redniBrojPreseka);
        
        StavkaRepositoryIml repo= new StavkaRepositoryIml();
        try {
        	//brojRacuna;
        	//datum;
        	//redniBrojPreseka;
        	
            
            Zaglavlje zag=new Zaglavlje();
            if(redniBrojPreseka<3)
            zag.setBrojPreseka(redniBrojPreseka);
            else
                zag.setBrojPreseka(2);
            
            zag.setBrojPromenaNaTeret(1);
            zag.setBrojPromenaUKorist(1);
            zag.setBrojRacuna("1");
            zag.setDatumNaloga(DatatypeFactory.newInstance().newXMLGregorianCalendar(new GregorianCalendar()));
            zag.setNovoStanje(new BigDecimal(4));
            zag.setPrethodnoStanje(new BigDecimal(4));
            zag.setUkupnoNaTeret(new BigDecimal(4));
            zag.setUkupnoUKorist(new BigDecimal(4));
            
            Stavke stav= new Stavke();
            

        	ArrayList<Stavka> a=repo.find("a");
            for(Stavka s:a){
            	stav.getStavka().add(s);
            }
        	stavke.value=stav;
            
            zaglavlje.value=zag;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	

}