package com.banka.services.izvod;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding.Use;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-24T15:56:56.867+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://codenotfound.com/services/izvod", name = "izvod")
@XmlSeeAlso({com.banka.models.zahtev.ObjectFactory.class, com.banka.models.presek.ObjectFactory.class})
@SOAPBinding(use=Use.LITERAL, parameterStyle=ParameterStyle.WRAPPED, style=Style.DOCUMENT)
public interface Izvod {

    @WebMethod(operationName = "GetPresek")
    @RequestWrapper(localName = "GetPresek", targetNamespace = "http://codenotfound.com/types/zahtev", className = "com.codenotfound.types.zahtev.GetPresek")
    @ResponseWrapper(localName = "GetPresekResponse", targetNamespace = "http://codenotfound.com/types/presek", className = "com.codenotfound.types.presek.GetPresekResponse")
    public void getPresek(
        @WebParam(name = "Broj_racuna", targetNamespace = "http://codenotfound.com/types/zahtev")
        java.lang.String brojRacuna,
        @WebParam(name = "Datum", targetNamespace = "http://codenotfound.com/types/zahtev")
        javax.xml.datatype.XMLGregorianCalendar datum,
        @WebParam(name = "Redni_broj_preseka", targetNamespace = "http://codenotfound.com/types/zahtev")
        int redniBrojPreseka,
        @WebParam(mode = WebParam.Mode.OUT, name = "Zaglavlje", targetNamespace = "http://codenotfound.com/types/presek")
        javax.xml.ws.Holder<com.banka.models.presek.GetPresekResponse.Zaglavlje> zaglavlje,
        @WebParam(mode = WebParam.Mode.OUT, name = "Stavke", targetNamespace = "http://codenotfound.com/types/presek")
        javax.xml.ws.Holder<com.banka.models.presek.GetPresekResponse.Stavke> stavke
    );
}
