package com.centralnaBanka.services.clearing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding.Use;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.centralnaBanka.models.mt102.NalogZaGrupnaPlacanja;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T15:35:44.010+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://codenotfound.com/services/clearing/", name = "clearing")
@XmlSeeAlso({com.centralnaBanka.models.mt102.ObjectFactory.class, com.centralnaBanka.models.mt900.ObjectFactory.class})
@SOAPBinding(use=Use.LITERAL, parameterStyle=ParameterStyle.WRAPPED, style=Style.DOCUMENT)
public interface Clearing {

    @WebMethod
    @RequestWrapper(localName = "clearing", targetNamespace = "http://codenotfound.com/types/mt102", className = "com.centralnaBanka.models.mt102.NalogZaGrupnaPlacanja")
    @ResponseWrapper(localName = "mt900", targetNamespace = "http://codenotfound.com/types/mt900", className = "com.centralnaBanka.models.mt900.Mt900")
    public void clearing(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ID_poruke", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.lang.String> idPoruke,
        @WebParam(mode = WebParam.Mode.INOUT, name = "SWIFT_kod_banke_duznika", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.lang.String> swiftKodBankeDuznika,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Obracunski_racun_banke_duznika", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.lang.String> obracunskiRacunBankeDuznika,
        @WebParam(name = "SWIFT_kod_banke_poverioca", targetNamespace = "http://codenotfound.com/types/mt102")
        java.lang.String swiftKodBankePoverioca,
        @WebParam(name = "Obracunski_racun_banke_poverioca", targetNamespace = "http://codenotfound.com/types/mt102")
        java.lang.String obracunskiRacunBankePoverioca,
        @WebParam(name = "Ukupan_iznos", targetNamespace = "http://codenotfound.com/types/mt102")
        java.math.BigDecimal ukupanIznos,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Sifra_valute", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.lang.String> sifraValute,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Datum_valute", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> datumValute,
        @WebParam(name = "Datum", targetNamespace = "http://codenotfound.com/types/mt102")
        javax.xml.datatype.XMLGregorianCalendar datum,
        @WebParam(name = "Placanja", targetNamespace = "http://codenotfound.com/types/mt102")
        NalogZaGrupnaPlacanja.Placanja placanja,
        @WebParam(mode = WebParam.Mode.OUT, name = "ID_poruke_naloga", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.lang.String> idPorukeNaloga,
        @WebParam(mode = WebParam.Mode.OUT, name = "Iznos", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.math.BigDecimal> iznos
    );
}
