package com.centralnaBanka.services.clearing;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T15:35:44.018+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "clearing", 
                  wsdlLocation = "classpath:wsdl/clearing.wsdl",
                  targetNamespace = "http://codenotfound.com/services/clearing/") 
public class Clearing_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://codenotfound.com/services/clearing/", "clearing");
    public final static QName ClearingSOAP = new QName("http://codenotfound.com/services/clearing/", "clearingSOAP");
    static {
        URL url = Clearing_Service.class.getClassLoader().getResource("wsdl/clearing.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(Clearing_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/clearing.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public Clearing_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Clearing_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Clearing_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Clearing_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Clearing_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Clearing_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Clearing
     */
    @WebEndpoint(name = "clearingSOAP")
    public Clearing getClearingSOAP() {
        return super.getPort(ClearingSOAP, Clearing.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Clearing
     */
    @WebEndpoint(name = "clearingSOAP")
    public Clearing getClearingSOAP(WebServiceFeature... features) {
        return super.getPort(ClearingSOAP, Clearing.class, features);
    }

}
