package com.firma.services.nalogzaprenos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-06-23T18:26:27.208+02:00
 * Generated source version: 3.1.7
 * 
 */


@WebServiceClient(name = "nalogzaprenos", 
                  wsdlLocation = "file:/C:/Users/user/Downloads/Desktop/git/XML/XML/firma/src/main/resources/wsdl/nalogzaprenos.wsdl",
                  targetNamespace = "http://codenotfound.com/services/nalogzaprenos") 
public class Nalogzaprenos_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://codenotfound.com/services/nalogzaprenos", "nalogzaprenos");
    public final static QName NalogzaprenosSOAP = new QName("http://codenotfound.com/services/nalogzaprenos", "nalogzaprenosSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/user/Downloads/Desktop/git/XML/XML/firma/src/main/resources/wsdl/nalogzaprenos.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Nalogzaprenos_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/user/Downloads/Desktop/git/XML/XML/firma/src/main/resources/wsdl/nalogzaprenos.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Nalogzaprenos_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Nalogzaprenos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Nalogzaprenos_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Nalogzaprenos_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Nalogzaprenos_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Nalogzaprenos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Nalogzaprenos
     */
    @WebEndpoint(name = "nalogzaprenosSOAP")
    public NalogzaprenosWrapped getNalogzaprenosSOAP() {
        return super.getPort(NalogzaprenosSOAP, NalogzaprenosWrapped.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Nalogzaprenos
     */
    @WebEndpoint(name = "nalogzaprenosSOAP")
    public NalogzaprenosWrapped getNalogzaprenosSOAP(WebServiceFeature... features) {
        return super.getPort(NalogzaprenosSOAP, NalogzaprenosWrapped.class, features);
    }

}
