package com.firma.services.nalogzaprenos;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-06-23T18:26:27.169+02:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://codenotfound.com/services/nalogzaprenos", 
name = "nalogzaprenos")
@XmlSeeAlso({com.firma.models.nalogzaprenos.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)
public interface NalogzaprenosWrapped {

    @WebMethod(operationName = "GetNalog")
    @Oneway
    @RequestWrapper(localName = "GetNalog", 
    targetNamespace = "http://codenotfound.com/types/nalogzaprenos", 
    className = "com.codenotfound.types.nalogzaprenos.GetNalog")
    public void getNalog(
        @WebParam(name = "IDPoruke", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        long idPoruke,
        @WebParam(name = "DuznikNalogodavac", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        java.lang.String duznikNalogodavac,
        @WebParam(name = "SvrhaPlacanja", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        java.lang.String svrhaPlacanja,
        @WebParam(name = "PrimalacPoverilac", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        java.lang.String primalacPoverilac,
        @WebParam(name = "DatumNaloga", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        javax.xml.datatype.XMLGregorianCalendar datumNaloga,
        @WebParam(name = "DatumValute", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        javax.xml.datatype.XMLGregorianCalendar datumValute,
        @WebParam(name = "RacunDuznika", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        java.lang.String racunDuznika,
        @WebParam(name = "ModelZaduzenja", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        int modelZaduzenja,
        @WebParam(name = "PozivNaBrojZaduzenja", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        java.lang.String pozivNaBrojZaduzenja,
        @WebParam(name = "RacunPoverioca", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        java.lang.String racunPoverioca,
        @WebParam(name = "ModelOdobrenja", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        int modelOdobrenja,
        @WebParam(name = "PozivNaBrojOdobrenja", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        java.lang.String pozivNaBrojOdobrenja,
        @WebParam(name = "Iznos", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        java.math.BigDecimal iznos,
        @WebParam(name = "OznakaValute", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        java.lang.String oznakaValute,
        @WebParam(name = "Hitno", targetNamespace = "http://codenotfound.com/types/nalogzaprenos")
        boolean hitno
    );
}
