package com.banka.services.rtgsprijem;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T13:20:21.982+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "rtgsPrijem", 
                  wsdlLocation = "classpath:wsdl/rtgsPrijem.wsdl",
                  targetNamespace = "http://codenotfound.com/services/rtgsPrijem") 
public class RtgsPrijem_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://codenotfound.com/services/rtgsPrijem", "rtgsPrijem");
    public final static QName RtgsSOAP = new QName("http://codenotfound.com/services/rtgsPrijem", "rtgsSOAP");
    static {
        URL url = RtgsPrijem_Service.class.getClassLoader().getResource("wsdl/rtgsPrijem.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RtgsPrijem_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/rtgsPrijem.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public RtgsPrijem_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RtgsPrijem_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RtgsPrijem_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RtgsPrijem_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RtgsPrijem_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RtgsPrijem_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RtgsPrijem
     */
    @WebEndpoint(name = "rtgsSOAP")
    public RtgsPrijem getRtgsSOAP() {
        return super.getPort(RtgsSOAP, RtgsPrijem.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RtgsPrijem
     */
    @WebEndpoint(name = "rtgsSOAP")
    public RtgsPrijem getRtgsSOAP(WebServiceFeature... features) {
        return super.getPort(RtgsSOAP, RtgsPrijem.class, features);
    }

}
