package com.banka.services.rtgsprijem;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding.Use;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

import com.banka.models.mt103.Mt103CT;
import com.banka.models.mt910.MT910CT;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T13:20:21.976+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://codenotfound.com/services/rtgsPrijem", name = "rtgsPrijem")
@XmlSeeAlso({com.banka.models.mt910.ObjectFactory.class, com.banka.models.mt103.ObjectFactory.class, com.banka.models.rtgsprijem.ObjectFactory.class})
@SOAPBinding(use=Use.LITERAL, parameterStyle=ParameterStyle.WRAPPED, style=Style.DOCUMENT)
public interface RtgsPrijem {

    @WebMethod
    @Oneway
    @RequestWrapper(localName = "rtgsPrijem", targetNamespace = "http://codenotfound.com/types/rtgsPrijem", className = "com.banka.models.rtgsprijem.RtgsPrijem")
    public void rtgsPrijem(
        @WebParam(name = "mt103", targetNamespace = "http://codenotfound.com/types/rtgsPrijem")
        Mt103CT mt103,
        @WebParam(name = "mt910", targetNamespace = "http://codenotfound.com/types/rtgsPrijem")
        MT910CT mt910
    );
}
