package com.centralnaBanka.services.rtgs;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-23T22:15:20.415+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "rtgs", 
                  wsdlLocation = "classpath:wsdl/rtgs.wsdl",
                  targetNamespace = "http://codenotfound.com/services/rtgs/") 
public class Rtgs_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://codenotfound.com/services/rtgs/", "rtgs");
    public final static QName RtgsSOAP = new QName("http://codenotfound.com/services/rtgs/", "rtgsSOAP");
    static {
        URL url = Rtgs_Service.class.getClassLoader().getResource("wsdl/rtgs.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(Rtgs_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/rtgs.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public Rtgs_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Rtgs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Rtgs_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Rtgs_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Rtgs_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Rtgs_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Rtgs
     */
    @WebEndpoint(name = "rtgsSOAP")
    public Rtgs getRtgsSOAP() {
        return super.getPort(RtgsSOAP, Rtgs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Rtgs
     */
    @WebEndpoint(name = "rtgsSOAP")
    public Rtgs getRtgsSOAP(WebServiceFeature... features) {
        return super.getPort(RtgsSOAP, Rtgs.class, features);
    }

}
