package com.centralnaBanka.services.rtgs;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding.Use;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-23T22:15:20.256+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://codenotfound.com/services/rtgs/", name = "rtgs")
@XmlSeeAlso({com.centralnaBanka.types.mt103.ObjectFactory.class, com.centralnaBanka.types.mt900.ObjectFactory.class})
@SOAPBinding(use=Use.LITERAL, parameterStyle=ParameterStyle.WRAPPED, style=Style.DOCUMENT)
public interface Rtgs {

    @WebMethod
    @RequestWrapper(localName = "rtgs", targetNamespace = "http://codenotfound.com/types/mt103", className = "com.codenotfound.types.mt103.Rtgs")
    @ResponseWrapper(localName = "mt900", targetNamespace = "http://codenotfound.com/types/mt900", className = "com.codenotfound.types.mt900.Mt900")
    public void rtgs(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ID_poruke", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.lang.String> idPoruke,
        @WebParam(mode = WebParam.Mode.INOUT, name = "SWIFT_kod_banke_duznika", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.lang.String> swiftKodBankeDuznika,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Obracunski_racun_banke_duznika", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.lang.String> obracunskiRacunBankeDuznika,
        @WebParam(name = "SWIFT_kod_banke_poverioca", targetNamespace = "http://codenotfound.com/types/mt103")
        java.lang.String swiftKodBankePoverioca,
        @WebParam(name = "Obracunski_racun_banke_poverioca", targetNamespace = "http://codenotfound.com/types/mt103")
        java.lang.String obracunskiRacunBankePoverioca,
        @WebParam(name = "Duznik-nalogodavac", targetNamespace = "http://codenotfound.com/types/mt103")
        java.lang.String duznikNalogodavac,
        @WebParam(name = "Svrha_placanja", targetNamespace = "http://codenotfound.com/types/mt103")
        java.lang.String svrhaPlacanja,
        @WebParam(name = "Primalac-poverilac", targetNamespace = "http://codenotfound.com/types/mt103")
        java.lang.String primalacPoverilac,
        @WebParam(name = "Datum_naloga", targetNamespace = "http://codenotfound.com/types/mt103")
        javax.xml.datatype.XMLGregorianCalendar datumNaloga,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Datum_valute", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> datumValute,
        @WebParam(name = "Racun_duznika", targetNamespace = "http://codenotfound.com/types/mt103")
        java.lang.String racunDuznika,
        @WebParam(name = "Model_zaduzenja", targetNamespace = "http://codenotfound.com/types/mt103")
        int modelZaduzenja,
        @WebParam(name = "Poziv_na_broj_zaduzenja", targetNamespace = "http://codenotfound.com/types/mt103")
        java.lang.String pozivNaBrojZaduzenja,
        @WebParam(name = "Racun_poverioca", targetNamespace = "http://codenotfound.com/types/mt103")
        java.lang.String racunPoverioca,
        @WebParam(name = "Model_odobrenja", targetNamespace = "http://codenotfound.com/types/mt103")
        int modelOdobrenja,
        @WebParam(name = "Poziv_na_broj_odobrenja", targetNamespace = "http://codenotfound.com/types/mt103")
        java.lang.String pozivNaBrojOdobrenja,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Iznos", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.math.BigDecimal> iznos,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Sifra_valute", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.lang.String> sifraValute,
        @WebParam(mode = WebParam.Mode.OUT, name = "ID_poruke_naloga", targetNamespace = "http://codenotfound.com/types/mt900")
        javax.xml.ws.Holder<java.lang.String> idPorukeNaloga
    );
}
