package com.banka.services.clearingprijem;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding.Use;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

import com.banka.models.mt910.MT910CT;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T16:13:29.498+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://codenotfound.com/services/clearingPrijem", name = "clearingPrijem")
@XmlSeeAlso({com.banka.models.mt910.ObjectFactory.class, com.banka.models.mt102.ObjectFactory.class, com.banka.models.clearingprijem.ObjectFactory.class})

@SOAPBinding(use=Use.LITERAL, parameterStyle=ParameterStyle.WRAPPED, style=Style.DOCUMENT)
public interface ClearingPrijem {

    @WebMethod
    @Oneway
    @RequestWrapper(localName = "clearingPrijem", targetNamespace = "http://codenotfound.com/types/clearingPrijem", className = "com.banka.models.clearingprijem.ClearingPrijem")
    public void clearingPrijem(
        @WebParam(name = "mt102", targetNamespace = "http://codenotfound.com/types/clearingPrijem")
        com.banka.models.mt102.NalogZaGrupnaPlacanja mt102,
        @WebParam(name = "mt910", targetNamespace = "http://codenotfound.com/types/clearingPrijem")
        MT910CT mt910
    );
}
